steps:
  - make:
      type: run
      from: slartibartfast/bedtools-buildenv
      cmd:
        - make
        - ./bin/bedtools  # Just print usage

  - package_tool:
      type: build
      from: ubuntu:14.04
      cmd: cp ./bin/bedtools /usr/bin
      entrypoint: /usr/bin/bedtools
      register:
        repo: slartibartfast/bedtools
        tag: v2.20.2-beta
